version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "2000:2000"
    volumes:
      - ./api:/usr/src/app
      # api_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - appnet
    # Ejecutar npm install en tiempo de arranque para garantizar dependencias.
    # Nota: esto añade tiempo al arranque pero evita errores cuando node_modules
    # en el volumen está vacío.
    #command: sh -c "npm install && npm run dev"

  app:
    build: ./app
    ports:
      - "3800:3200"
    volumes:
      - ./app:/usr/src/app
      # app_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - appnet
  


volumes:
  app_node_modules:
  api_node_modules:

networks:
  appnet:
    driver: bridge